version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs
    ports:
      - 443:443
  rundeck:
    image: rundeck/rundeck:4.6.0
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: https://localhost
      RUNDECK_SERVER_FORWARDED: "true"